import { NextResponse } from 'next/server';
import crypto from 'crypto';

// In a real app, this would be in .env
const SECRET_KEY = process.env.DONATION_SECRET_KEY || 'default-insecure-secret-for-demo-only';

export async function POST() {
    try {
        // 1. Simulate payment processing delay
        await new Promise((resolve) => setTimeout(resolve, 1500));

        // 2. Generate a random ID
        const randomId = crypto.randomBytes(4).toString('hex').toUpperCase();

        // 3. Create a signature
        // We sign the randomId to ensure the code was generated by us
        const signature = crypto
            .createHmac('sha256', SECRET_KEY)
            .update(randomId)
            .digest('hex')
            .substring(0, 8)
            .toUpperCase();

        // 4. Construct the code
        const code = `DD-PRO-${randomId}-${signature}`;

        return NextResponse.json({ success: true, code });
    } catch (error) {
        console.error('Donation error:', error);
        return NextResponse.json(
            { success: false, error: 'Payment processing failed' },
            { status: 500 }
        );
    }
}
